### ISSUE TITLE
Group presentation

### ISSUE THREAD

**Issue by dfsalam** [kensteph/Recipe-Group-project#15]

**Comment by tufoinnkuo10** [comment]
Hi @Kossi-stack

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ Board well organized
✅ Task well shared

## Required Changes ♻️

Great job so far. please, you are missing some task in your board. Remember, these tasks are to help keep you on track. Please add the below task to your board.
- [ ] Food list (description 👇🏾 )
- Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
- Should lead to a form that allows users to add new food.
- [ ] General shopping list view (description 👇🏾 )
- Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
- Should count the total food items and total price of the missing food.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Gambit142** [comment]
Hi @dfsalam @kensteph @V0pe 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban board correctly ✔️ 
- Tasks are shared in an even manner ✔️ 
- Each task has a title, description and number of points ✔️
- All project requirements are represented ✔️ 

### Optional Suggestion

- I would advise you to delete the **_General shopping list view_** card from the Kanban board because you are a team of three and it should only be implemented by teams who have two members only. 

![image](https://github.com/kensteph/Recipe-Group-project/assets/77106962/7b3ffabb-5e73-4698-a465-be663b200a12)

#### You can confirm by clicking this [link](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) to check the requirements again. 👍 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by addod19** [comment]
## Hi TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because you submitted a project that is already approved and closed

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
